apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: rhoai-model-registries
  finalizers:
    - modelregistry.opendatahub.io/finalizer
spec:
  grpc:
    port: 9090
  kubeRBACProxy:
    port: 8443
    routePort: 443
    serviceRoute: enabled
  mysql:
    database: {{ .Values.mysql.database }}
    host: {{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local
    passwordSecret:
      key: database-password
      name: {{ .Release.Name }}-db
    port: 3306
    skipDBCreation: false
    username: {{ .Values.mysql.user }}
  rest:
    port: 8080
    serviceRoute: disabled
