apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    {{- with .Values.connections }}
    opendatahub.io/connections: {{ . | quote }}
    {{- end }}
    opendatahub.io/hardware-profile-name: {{ .Values.hardwareProfileName }}
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/model-type: generative
    openshift.io/description: ""
    openshift.io/display-name: {{ .Values.modelname }}
    security.opendatahub.io/enable-auth: {{ toString .Values.enableAuth | quote }}
    serving.kserve.io/deploymentMode: RawDeployment
  finalizers:
  - inferenceservice.finalizers
  - odh.inferenceservice.finalizers
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
  name: {{ .Values.modelname }}
  namespace: {{ .Values.namespace }}
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      runtime: {{ .Values.runtime }}
      storageUri: {{ .Values.uri }}
