{{- if eq (toString .Values.enableAuth) "true" }}
{{- $sa := printf "%s-sa" .Values.modelname }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  secrets:
    - name: {{ $sa }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $sa }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    kubernetes.io/service-account.name: {{ $sa }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $sa }}-role
  namespace: {{ .Values.namespace }}
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups:
      - serving.kserve.io
    resources:
      - inferenceservices
    resourceNames:
      - {{ .Values.modelname }}
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $sa }}-rolebinding
  namespace: {{ .Values.namespace }}
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: {{ $sa }}
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $sa }}-role
{{- end }}
