
profileName: nvidia-gpu-profile

hardwareProfile:
  identifiers:
    - resourceType: CPU
      identifier: cpu
      displayName: CPU
      minCount: 8
      maxCount: 16
      defaultCount: 12
    - resourceType: Memory
      identifier: memory
      displayName: Memory
      minCount: 32Gi
      maxCount: 64Gi
      defaultCount: 48Gi
    - resourceType: Accelerator
      identifier: nvidia.com/gpu
      displayName: Accelerator
      minCount: 1
      maxCount: 1
      defaultCount: 1
  scheduling:
    node:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
